#!/bin/bash

# 🔍 Firebase Private Key 진단 스크립트
# Cloudflare Pages 환경 변수의 Firebase Private Key 형식을 확인합니다.

echo "=========================================="
echo "Firebase Private Key 형식 진단"
echo "=========================================="
echo ""

echo "📋 현재 설정해야 할 값:"
echo ""
echo "FIREBASE_PROJECT_ID: urteam-live-commerce-5b284"
echo "FIREBASE_CLIENT_EMAIL: firebase-adminsdk-fbsvc@urteam-live-commerce-5b284.iam.gserviceaccount.com"
echo ""

echo "🔑 FIREBASE_PRIVATE_KEY 형식 요구사항:"
echo ""
echo "❌ 잘못된 형식 (리터럴 \\n):"
echo '    "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQ..."'
echo ""
echo "✅ 올바른 형식 (실제 줄바꿈):"
echo "    -----BEGIN PRIVATE KEY-----"
echo "    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDE/s3PltvNta+W"
echo "    ..."
echo "    -----END PRIVATE KEY-----"
echo ""

echo "=========================================="
echo "📥 새 Private Key 생성 방법"
echo "=========================================="
echo ""
echo "1. Firebase Console 접속:"
echo "   https://console.firebase.google.com/project/urteam-live-commerce-5b284/settings/serviceaccounts/adminsdk"
echo ""
echo "2. 'Generate new private key' 버튼 클릭"
echo ""
echo "3. JSON 파일 다운로드 (예: urteam-live-commerce-5b284-firebase-adminsdk-xxxxx.json)"
echo ""
echo "4. JSON 파일 열기 → 'private_key' 값 복사"
echo ""

echo "=========================================="
echo "🔧 줄바꿈 변환 방법 (3가지)"
echo "=========================================="
echo ""

echo "방법 A: 온라인 도구"
echo "--------"
echo "1. https://www.freeformatter.com/json-escape.html 접속"
echo '2. 복사한 private_key 값을 붙여넣기 (예: "-----BEGIN PRIVATE KEY-----\\n...")'
echo "3. 'Unescape' 버튼 클릭"
echo "4. 변환된 결과 복사"
echo ""

echo "방법 B: VS Code / 텍스트 에디터"
echo "--------"
echo "1. VS Code 열기 → 새 파일 생성"
echo "2. 복사한 private_key 값 붙여넣기"
echo '3. Find/Replace (Ctrl+H): "\\n" → Enter (실제 줄바꿈)'
echo "4. Replace All 클릭"
echo "5. 변환된 결과 복사"
echo ""

echo "방법 C: JavaScript Console (Browser DevTools)"
echo "--------"
echo "1. Browser에서 F12 → Console 탭"
echo "2. 다음 코드 실행:"
echo ""
echo "const escapedKey = \`YOUR_PRIVATE_KEY_HERE\`;"
echo "const unescapedKey = escapedKey.replace(/\\\\n/g, '\\n');"
echo "console.log(unescapedKey);"
echo "copy(unescapedKey); // 자동으로 클립보드에 복사"
echo ""
echo "3. 출력된 결과 복사 (또는 copy() 함수로 자동 복사)"
echo ""

echo "=========================================="
echo "☁️  Cloudflare Dashboard 업데이트"
echo "=========================================="
echo ""
echo "1. https://dash.cloudflare.com/ 접속"
echo ""
echo "2. Workers & Pages → ur-live → Settings → Environment variables"
echo ""
echo "3. Production 섹션에서 'FIREBASE_PRIVATE_KEY' 변수 찾기"
echo ""
echo "4. 'Edit' 버튼 클릭"
echo ""
echo "5. 변환된 private key 붙여넣기 (실제 줄바꿈 포함)"
echo ""
echo "6. 'Save' 버튼 클릭"
echo ""

echo "=========================================="
echo "🚀 재배포 및 테스트"
echo "=========================================="
echo ""
echo "1. Cloudflare Dashboard → Workers & Pages → ur-live → Deployments"
echo ""
echo "2. 최신 deployment의 '...' 메뉴 → 'Retry deployment' 클릭"
echo ""
echo "3. 5-10분 대기 (배포 완료)"
echo ""
echo "4. 테스트:"
echo "   - Incognito 모드로 https://live.ur-team.com 접속"
echo "   - 카카오 로그인 시도"
echo "   - Browser DevTools → Console 확인"
echo "   - 'Invalid PKCS8 input' 오류가 사라졌는지 확인"
echo ""

echo "=========================================="
echo "✅ 성공 기준"
echo "=========================================="
echo ""
echo "다음 조건들이 모두 충족되어야 합니다:"
echo ""
echo "  ✓ 배포 완료 (5-10분)"
echo "  ✓ 사이트 로드 성공 (404 없음)"
echo "  ✓ 카카오 로그인 → 인증 페이지 이동"
echo "  ✓ 인증 완료 → 프로필 페이지로 리다이렉트"
echo "  ✓ Console에 'Invalid PKCS8 input' 오류 없음"
echo "  ✓ Console에 'auth/api-key-not-valid' 오류 없음"
echo ""

echo "=========================================="
echo "📞 추가 지원"
echo "=========================================="
echo ""
echo "문제가 지속되면 다음을 확인하세요:"
echo ""
echo "1. Cloudflare Worker 로그:"
echo "   https://dash.cloudflare.com/ → Workers & Pages → ur-live → Logs"
echo ""
echo "2. GitHub Actions 로그:"
echo "   https://github.com/tobe2111/ur-live/actions"
echo ""
echo "3. Firebase Authentication 설정:"
echo "   https://console.firebase.google.com/project/urteam-live-commerce-5b284/authentication/providers"
echo ""
echo "4. Kakao Developers Console:"
echo "   https://developers.kakao.com/console/app"
echo ""

echo "=========================================="
echo ""
echo "🎯 다음 단계: Firebase Console에서 새 Private Key를 생성하고"
echo "   위의 방법 중 하나로 줄바꿈을 변환한 후 Cloudflare에 업데이트하세요."
echo ""
