#!/bin/bash

echo "========================================="
echo "NicePay 테스트 환경 설정"
echo "========================================="
echo ""
echo "공식 NicePay 테스트 계정 정보:"
echo ""
echo "MID: nictest00m"
echo "Merchant Key: (NicePay 공식 테스트 키)"
echo "Client ID: S2_d5ec29558e9d46419bf01eb828ca0834"
echo ""
echo "테스트 카드:"
echo "  - 카드번호: 5412-3456-7890-1234"
echo "  - 유효기간: 12/25"
echo "  - CVC: 123"
echo ""
echo "========================================="
echo "환경 변수 설정 중..."
echo "========================================="

# Cloudflare에 테스트 환경 변수 설정
echo ""
echo "✅ 다음 명령어로 테스트 환경 설정:"
echo ""
echo "npx wrangler pages secret put NICEPAY_CLIENT_ID --project-name toss-live-commerce"
echo "입력값: S2_d5ec29558e9d46419bf01eb828ca0834"
echo ""
